### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4) - Error when running ampliconclassifier inside ampliconsuite

### ISSUE THREAD

**Issue by DSchreyer** [AmpliconSuite/AmpliconClassifier#19]
Dear Maintainers, 
I got this error when trying to run ampliconsuite inside nextflow, so I am unsure if this occurs because of nextflow or maybe the issue arises on your side. 
I also tested the conda amplicon_classifier.py script on the same input data and I get the same error. The command I am running is:

`/home/local/BICR/dschreye/miniconda3/envs/ampliconsuite/bin/amplicon_classifier.py -i test.input --ref GRCh38`

The cycles files look okay. and ampl
```
amplicon_classifier.py -i test.input --ref GRCh38
AmpliconClassifier 1.1.0
/home/local/BICR/dschreye/miniconda3/envs/ampliconsuite/bin/amplicon_classifier.py -i test.input --ref GRCh38
reading /home/local/BICR/dschreye/src/AmpliconArchitect/data_repo/GRCh38/Genes_hg38.gff
read 22998 genes

SRR8236746_05perc amplicon1
Traceback (most recent call last):
  File "/home/local/BICR/dschreye/miniconda3/envs/ampliconsuite/bin/amplicon_classifier.py", line 1149, in <module>
    run_classification(segSeqD, cycleList, cycleCNs)
  File "/home/local/BICR/dschreye/miniconda3/envs/ampliconsuite/bin/amplicon_classifier.py", line 797, in run_classification
    fb_edges, fb_readcount, fb_prop, maxCN, tot_over_min_cn = compute_f_from_AA_graph(graphFile, args.add_chr_tag)
ValueError: not enough values to unpack (expected 5, got 4)
```

This is the ampliconsuite log output:
```Running amplified_intervals
[root:INFO]     python /mnt/data_disk/R01/dschreye/work3/conda/env-65ae7ae2137b295abe23230c5a058dac/lib/python3.10/site-packages/ampliconarchitectlib/amplified_intervals.py --ref GRCh38 --bed /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6//SRR8236746_05perc.md_CNV_CALLS_pre_filtered.bed --bam SRR8236746_05perc.md.bam --gain 4.5 --cnsize_min 50000 --out /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_AA_CNV_SEEDS
[root:INFO]     python /mnt/data_disk/R01/dschreye/work3/conda/env-65ae7ae2137b295abe23230c5a058dac/lib/python3.10/site-packages/ampliconarchitectlib/AmpliconArchitect.py --ref GRCh38 --downsample 10 --bed /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_AA_CNV_SEEDS.bed --bam SRR8236746_05perc.md.bam --runmode FULL --extendmode EXPLORE --out /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_AA_results//SRR8236746_05perc
[root:INFO]
Running AC
[root:INFO]     /mnt/data_disk/R01/dschreye/work3/conda/env-65ae7ae2137b295abe23230c5a058dac/bin/make_input.sh /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_AA_results/ /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc
[root:INFO]     python3 /mnt/data_disk/R01/dschreye/work3/conda/env-65ae7ae2137b295abe23230c5a058dac/bin/amplicon_classifier.py -i /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc.input --ref GRCh38 -o /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc --report_complexity
[root:INFO]     python3 /mnt/data_disk/R01/dschreye/work3/conda/env-65ae7ae2137b295abe23230c5a058dac/bin/make_results_table.py -i /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc.input --classification_file /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc_amplicon_classification_profiles.tsv --summary_map /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_classification/SRR8236746_05perc_summary_map.txt --cnv_bed /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_cnvkit_output/SRR8236746_05perc.md_CNV_CALLS.bed --run_metadata_file /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_run_metadata.json --sample_metadata_file /mnt/data_disk/R01/dschreye/work3/35/41ffaa5ce57ee2934349cf4baf82d6/SRR8236746_05perc_sample_metadata.json
[root:ERROR]    Detected error during AC stage
```

**Comment by jluebeck** [comment]
This is an error in AmpliconClassifier (AC) v1.1.0 and is fixed in AC version 1.1.1 (embedded in AmpliconSuite-pipeline package version 1.2.1 and on).
